title: Jacob Michael Green # your name (or website title) here
logo: "/images/Jacob_Green.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in the URI BES department with an specialization in Evolution and Marine Biology 
  <br><br>
  I am broadly interesting in Bioinformatics, Immunology, and Marine Biology
  <br><br>
  <a href="https://www.linkedin.com/in/madmolecularman/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
